# Generated by Django 2.2 on 2019-12-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('count', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('DOING', 'doing'), ('REVIEW', 'review'), ('CLOSED', 'closed')], max_length=50, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
